/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AddRoomController;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DBAddRoom;
import model.DBConnection;

/**
 *
 * @author Isuru
 */
public class AddRoom extends javax.swing.JFrame {

    /**
     * Creates new form ManageRoom
     */
    public AddRoom() {
        initComponents();
    }
public void clearField(){
    roomNumberTF.setText("");
    priceTF.setText("");
    bedCMB.setSelectedIndex(0);
    roomTypeCMB.setSelectedIndex(0);
    
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        roomNumberTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        roomTypeCMB = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        bedCMB = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        priceTF = new javax.swing.JTextField();
        addRoomBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Room Page");
        setLocation(new java.awt.Point(50, 118));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1750, 810));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-hotel-building-64.png"))); // NOI18N
        jLabel1.setText("Add Room Page");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 440, 100));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cl.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 20, 90, 70));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Room Number", "Room Type", "Bed", "Price", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 102, 1060, 510));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Room Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 110, -1, -1));

        roomNumberTF.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(roomNumberTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 160, 530, 34));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Room Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 220, -1, -1));

        roomTypeCMB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        roomTypeCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "A/C", "Non A/C" }));
        getContentPane().add(roomTypeCMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 270, 530, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Bed");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 330, -1, -1));

        bedCMB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bedCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Single", "Double", "Triple" }));
        getContentPane().add(bedCMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 380, 530, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Price Per Day");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 440, 200, -1));

        priceTF.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(priceTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 490, 530, 34));

        addRoomBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addRoomBtn.setText("Add Room");
        addRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addRoomBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 570, -1, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 570, 160, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/riLo85baT.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomBtnActionPerformed
        // TODO add your handling code here:
        String roomNumber=roomNumberTF.getText();
        String roomType = roomTypeCMB.getSelectedItem().toString();
        String bed = bedCMB.getSelectedItem().toString();
        String price = priceTF.getText();
        if("".equals(roomNumber)||"".equals(price)||"Select".equals(bed)||"Select".equals(roomType)){
            AddRoomController.AddRoomError();
        }else{
        AddRoomController.AddRoom(roomNumber,roomType,bed,price);
        setVisible(false);
        new AddRoom().setVisible(true); 
        }
        
    }//GEN-LAST:event_addRoomBtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ResultSet rs=new DBAddRoom().DisplayAddRoom();
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
        try {
            Vector v;
            while(rs.next()){
                v = new Vector();
                v.add(rs.getString("roomNo"));
                v.add(rs.getString("roomType"));
                v.add(rs.getString("bed"));
                v.add(rs.getString("price"));
                v.add(rs.getString("status"));
                dtm.addRow(v);
            }
            DBConnection.closeCon();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formComponentShown

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRoomBtn;
    private javax.swing.JComboBox<String> bedCMB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField priceTF;
    private javax.swing.JTextField roomNumberTF;
    private javax.swing.JComboBox<String> roomTypeCMB;
    // End of variables declaration//GEN-END:variables
}
