/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CustomerCheckInController;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import model.DBConnection;
import model.DBCustomerCheckIn;

/**
 *
 * @author Isuru
 */
public class CustomerCheckIn extends javax.swing.JFrame {

    /**
     * Creates new form CustomerCheckIn
     */
    public CustomerCheckIn() {
        initComponents();
        checkInDateTF.setEditable(false);
        priceTF.setEditable(false);
        SimpleDateFormat myFormat=new SimpleDateFormat("yyyy/MM/dd");
        Calendar cal=Calendar.getInstance();
        checkInDateTF.setText(myFormat.format(cal.getTime()));
    }
    String bed;
    String roomType;
    String roomNumber;
    String price;
    
    
    public void roomDetails(){
        roomNumberCMB.removeAllItems();
        priceTF.setText("");
        bed=(String)bedCMB.getSelectedItem();
        roomType=(String)roomTypeCMB.getSelectedItem();
        try {
            ResultSet rs=new DBCustomerCheckIn().GetRoomDetails(bed,roomType);
            
            while(rs.next()){
                roomNumberCMB.addItem(rs.getString(1));
            }
            DBConnection.closeCon();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void clearField(){
    nameTF.setText("");
    mobleNumberTF.setText("");
    nationalityTF.setText("");
    emailTF.setText("");
    idProofTF.setText("");
    addressTF.setText("");    
    priceTF.setText("");
    genderCMB.setSelectedIndex(0);
    bedCMB.setSelectedIndex(0);
    roomTypeCMB.setSelectedIndex(0);
    roomNumberCMB.removeAllItems();
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mobleNumberTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nationalityTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        genderCMB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        idProofTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        addressTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        checkInDateTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bedCMB = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        roomTypeCMB = new javax.swing.JComboBox<>();
        roomNumberCMB = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        priceTF = new javax.swing.JTextField();
        bookRoomBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 118));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1750, 810));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cus in.png"))); // NOI18N
        jLabel1.setText("Customer Check IN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 420, 70));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cl.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 20, 90, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        nameTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 360, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Mobile Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        mobleNumberTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(mobleNumberTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 360, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Nationality");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        nationalityTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(nationalityTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 360, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        genderCMB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        genderCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        getContentPane().add(genderCMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 360, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));

        emailTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(emailTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 360, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("ID Proof");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        idProofTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(idProofTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 350, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, -1, -1));

        addressTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(addressTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 350, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Check IN Date (today)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, 28));

        checkInDateTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(checkInDateTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 350, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Bed");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 210, -1, -1));

        bedCMB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bedCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple" }));
        bedCMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bedCMBActionPerformed(evt);
            }
        });
        getContentPane().add(bedCMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 260, 510, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Room Type");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Room Number");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 310, -1, -1));

        roomTypeCMB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        roomTypeCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A/C", "Non A/C" }));
        roomTypeCMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomTypeCMBActionPerformed(evt);
            }
        });
        getContentPane().add(roomTypeCMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 160, 510, -1));

        roomNumberCMB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        roomNumberCMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNumberCMBActionPerformed(evt);
            }
        });
        getContentPane().add(roomNumberCMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 350, 510, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Price");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 400, -1, -1));

        priceTF.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        priceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTFActionPerformed(evt);
            }
        });
        getContentPane().add(priceTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, 340, -1));

        bookRoomBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bookRoomBtn.setText("Book Room");
        bookRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookRoomBtnActionPerformed(evt);
            }
        });
        getContentPane().add(bookRoomBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 530, 180, -1));

        clearBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 530, 170, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/riLo85baT.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1750, 810));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        clearField();
        
    }//GEN-LAST:event_clearBtnActionPerformed

    private void bedCMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bedCMBActionPerformed
        // TODO add your handling code here:
        roomDetails();
    }//GEN-LAST:event_bedCMBActionPerformed

    private void roomTypeCMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomTypeCMBActionPerformed
        // TODO add your handling code here:
        roomDetails();
    }//GEN-LAST:event_roomTypeCMBActionPerformed

    private void roomNumberCMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNumberCMBActionPerformed
        // TODO add your handling code here:
        roomNumber=(String)roomNumberCMB.getSelectedItem();
        try {
            ResultSet rs=new DBCustomerCheckIn().GetRoomDetails2(roomNumber);
            while(rs.next()){
                priceTF.setText(rs.getString(4));
            }
            DBConnection.closeCon();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_roomNumberCMBActionPerformed

    private void priceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTFActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_priceTFActionPerformed

    private void bookRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookRoomBtnActionPerformed
        // TODO add your handling code here:
        
        String name=nameTF.getText();
        String mobileNumber=mobleNumberTF.getText();
        String nationality=nationalityTF.getText();
        String gender=(String)genderCMB.getSelectedItem();
        String email=emailTF.getText();
        String idProof=idProofTF.getText();
        String address=addressTF.getText();
        String checkIn=checkInDateTF.getText();
        String bed=(String)bedCMB.getSelectedItem();
        String roomType=(String)roomTypeCMB.getSelectedItem();
        String roomNumber=(String)roomNumberCMB.getSelectedItem();
        String price=priceTF.getText();
        
        if(!price.equals("")&&!name.equals("")&&!mobleNumberTF.equals("")&&!nationalityTF.equals("")&&!emailTF.equals("")&&!idProofTF.equals("")&&!addressTF.equals("")){
            CustomerCheckInController.UpdateBooking(roomNumber);            
            CustomerCheckInController.AddCustomer(name, mobileNumber, nationality, gender, email, idProof, address, checkIn, roomNumber, bed, roomType, price);
            clearField();
        }else{
            CustomerCheckInController.AddCustomerNotFill();
        }
        
    }//GEN-LAST:event_bookRoomBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCheckIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTF;
    private javax.swing.JComboBox<String> bedCMB;
    private javax.swing.JButton bookRoomBtn;
    private javax.swing.JTextField checkInDateTF;
    private javax.swing.JButton clearBtn;
    private javax.swing.JTextField emailTF;
    private javax.swing.JComboBox<String> genderCMB;
    private javax.swing.JTextField idProofTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mobleNumberTF;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField nationalityTF;
    private javax.swing.JTextField priceTF;
    private javax.swing.JComboBox<String> roomNumberCMB;
    private javax.swing.JComboBox<String> roomTypeCMB;
    // End of variables declaration//GEN-END:variables
}
