/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import controller.CustomerCheckOutController;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import model.DBConnection;
import model.DBCustomerCheckOut;

/**
 *
 * @author Isuru
 */
public class CustomerCheckOut extends javax.swing.JFrame {

    /**
     * Creates new form CustomerCheckOut
     */
    public CustomerCheckOut() {
        initComponents();
        
        customerIdNumberTF.setEditable(false);
        customerNameTF.setEditable(false);
        checkInDateTF.setEditable(false);
        checkOutDateTF.setEditable(false);
        customerMobileNumberTF.setEditable(false);
        pricePerDayForRoomTF.setEditable(false);
        numberOfDaysStayTF.setEditable(false);
        totalAmountTF.setEditable(false);
        emailTF.setEditable(false);
        customerNationalityTF.setEditable(false);
        customerNationalityIdNumberTF.setEditable(true);
        genderTF.setEditable(false);
        addressTF.setEditable(false);
        roomTypeTF.setEditable(false);
        bedTF.setEditable(false);
    }

    public void clearField(){
    customerNameTF.setText("");
        customerMobileNumberTF.setText("");
        customerNationalityTF.setText("");
        genderTF.setText("");
        emailTF.setText("");
        customerNationalityIdNumberTF.setText("");
        addressTF.setText("");
        checkInDateTF.setText("");
        pricePerDayForRoomTF.setText("");
        numberOfDaysStayTF.setText("");
        totalAmountTF.setText("");
        checkOutDateTF.setText("");
        customerIdNumberTF.setText("");
        roomNumberTF.setText("");
        roomTypeTF.setText("");
        bedTF.setText("");
        roomNumberTF.setEditable(true);
        
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        roomNumberTF = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        customerNameTF = new javax.swing.JTextField();
        checkInDateTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        checkOutDateTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        customerMobileNumberTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pricePerDayForRoomTF = new javax.swing.JTextField();
        numberOfDaysStayTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        totalAmountTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        printBill = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        customerNationalityTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        genderTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        customerNationalityIdNumberTF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        addressTF = new javax.swing.JTextField();
        resetBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        customerIdNumberTF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        roomTypeTF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        bedTF = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1750, 810));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/out.png"))); // NOI18N
        jLabel1.setText("Customer Check Out");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 22, 450, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cl.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1660, 20, 80, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Room Number ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, -1));

        roomNumberTF.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        roomNumberTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNumberTFActionPerformed(evt);
            }
        });
        getContentPane().add(roomNumberTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, 170, -1));

        searchBtn.setBackground(java.awt.Color.white);
        searchBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        searchBtn.setForeground(java.awt.Color.blue);
        searchBtn.setText("Search");
        searchBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 80, 120, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Mobile Number", "Nationality", "Gender", "Email", "Id Number", "Address", "Check In Date", "Room Number", "Bed", "Room Type", "Price Per Day"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 1726, 250));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Coustomer Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Check In Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 310, -1, -1));

        customerNameTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        customerNameTF.setPreferredSize(new java.awt.Dimension(30, 30));
        getContentPane().add(customerNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 240, 30));

        checkInDateTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkInDateTF.setPreferredSize(new java.awt.Dimension(30, 30));
        getContentPane().add(checkInDateTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 340, 270, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Check Out Date(Today)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, -1, 30));

        checkOutDateTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkOutDateTF.setPreferredSize(new java.awt.Dimension(30, 30));
        checkOutDateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutDateTFActionPerformed(evt);
            }
        });
        getContentPane().add(checkOutDateTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 240, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Customer Mobile Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 210, 285, 20));

        customerMobileNumberTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        customerMobileNumberTF.setPreferredSize(new java.awt.Dimension(30, 30));
        getContentPane().add(customerMobileNumberTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 250, 260, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Price Per Day For Room");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, 230, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Number of Days Stay");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        pricePerDayForRoomTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pricePerDayForRoomTF.setPreferredSize(new java.awt.Dimension(30, 30));
        getContentPane().add(pricePerDayForRoomTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 250, 30));

        numberOfDaysStayTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        numberOfDaysStayTF.setPreferredSize(new java.awt.Dimension(30, 30));
        getContentPane().add(numberOfDaysStayTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 240, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("Total Amount ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 400, -1, -1));

        totalAmountTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalAmountTF.setPreferredSize(new java.awt.Dimension(30, 30));
        getContentPane().add(totalAmountTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 430, 260, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Email");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 210, -1, 20));

        emailTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emailTF.setPreferredSize(new java.awt.Dimension(30, 30));
        getContentPane().add(emailTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 250, 270, 30));

        printBill.setBackground(java.awt.Color.green);
        printBill.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        printBill.setText("Print Bill");
        printBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBillActionPerformed(evt);
            }
        });
        getContentPane().add(printBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 120, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Customer Nationality");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 210, 20));

        customerNationalityTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        customerNationalityTF.setPreferredSize(new java.awt.Dimension(30, 30));
        getContentPane().add(customerNationalityTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 240, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Gender");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 90, 20));

        genderTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        genderTF.setPreferredSize(new java.awt.Dimension(30, 30));
        getContentPane().add(genderTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 250, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("National ID Number");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, -1, -1));

        customerNationalityIdNumberTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        customerNationalityIdNumberTF.setPreferredSize(new java.awt.Dimension(30, 30));
        getContentPane().add(customerNationalityIdNumberTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 240, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Address");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, 20));

        addressTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addressTF.setPreferredSize(new java.awt.Dimension(30, 30));
        getContentPane().add(addressTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 240, 30));

        resetBtn.setBackground(java.awt.Color.white);
        resetBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        resetBtn.setForeground(java.awt.Color.blue);
        resetBtn.setText("Reset");
        resetBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        getContentPane().add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 80, 110, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Customer Id Number");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, -1, -1));

        customerIdNumberTF.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(customerIdNumberTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, 350, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Room Type");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, -1, -1));

        roomTypeTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        roomTypeTF.setPreferredSize(new java.awt.Dimension(30, 30));
        getContentPane().add(roomTypeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, 250, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Bed");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 300, -1, 20));

        bedTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bedTF.setPreferredSize(new java.awt.Dimension(30, 30));
        getContentPane().add(bedTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 340, 260, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/riLo85baT.jpg"))); // NOI18N
        jLabel18.setText("jLabel18");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1750, 1050));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkOutDateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutDateTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkOutDateTFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
        ResultSet rs = new DBCustomerCheckOut().DisplayCustomerCheckOutTable();
        DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
        try {
            Vector v;
            while(rs.next()){
                v = new Vector();
                v.add(rs.getString("id"));
                v.add(rs.getString("name"));
                v.add(rs.getString("mobileNumber"));
                v.add(rs.getString("nationality"));
                v.add(rs.getString("gender"));
                v.add(rs.getString("email"));
                v.add(rs.getString("idProof"));
                v.add(rs.getString("address"));
                v.add(rs.getString("checkIn"));
                v.add(rs.getString("roomNo"));
                v.add(rs.getString("bed"));
                v.add(rs.getString("roomType"));
                v.add(rs.getString("pricePerDay"));
                dtm.addRow(v);
            }
            DBConnection.closeCon();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formComponentShown

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String roomNumber=roomNumberTF.getText();
        try {
         
        ResultSet rs=new DBCustomerCheckOut().DisplayCustomerCheckOut(roomNumber);
        if(rs.next()){
            CustomerCheckOutController.DisplayInformationCustomerCheckOut();
            roomNumberTF.setEditable(false);
            customerIdNumberTF.setText(rs.getString(1));
            customerNameTF.setText(rs.getString(2));
            customerMobileNumberTF.setText(rs.getString(3));
            customerNationalityTF.setText(rs.getString(4));
            genderTF.setText(rs.getString(5));
            emailTF.setText(rs.getString(6));
            customerNationalityIdNumberTF.setText(rs.getString(7));
            addressTF.setText(rs.getString(8));
            checkInDateTF.setText(rs.getString(9));
            pricePerDayForRoomTF.setText(rs.getString(13));
            roomTypeTF.setText(rs.getString(12));
            bedTF.setText(rs.getString(11));
            
            SimpleDateFormat myFormat=new SimpleDateFormat("yyyy/MM/dd");
            Calendar cal=Calendar.getInstance();
            checkOutDateTF.setText(myFormat.format(cal.getTime()));
            String dateCheckInString=checkInDateTF.getText();
            
            Date dateChekIn=myFormat.parse(dateCheckInString);
            String dateAfterString=myFormat.format(cal.getTime());
            Date dateAfter=myFormat.parse(dateAfterString);
            long difference=dateAfter.getTime()- dateChekIn.getTime();
            int noOfDayStay=(int) (difference/(1000*60*60*24));
            
            if(noOfDayStay==0){
                noOfDayStay=1;
                numberOfDaysStayTF.setText(String.valueOf(noOfDayStay));
                float price=Float.parseFloat(pricePerDayForRoomTF.getText());    
                totalAmountTF.setText(String.valueOf(noOfDayStay*price));
            }else{
                noOfDayStay++;
                numberOfDaysStayTF.setText(String.valueOf(noOfDayStay));
                float price=Float.parseFloat(pricePerDayForRoomTF.getText());    
                totalAmountTF.setText(String.valueOf(noOfDayStay*price));
            }
                
         }else{
            CustomerCheckOutController.DisplayCustomerErrorCheckOut();
        }
        DBConnection.closeCon();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_searchBtnActionPerformed

    private void roomNumberTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNumberTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomNumberTFActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void printBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBillActionPerformed
        // TODO add your handling code here:
        String id;
        id = customerIdNumberTF.getText();
        String name=customerNameTF.getText();
        String mobileNumber=customerMobileNumberTF.getText();
        String email=emailTF.getText();
        String checkOut=checkOutDateTF.getText();
        String numberOfDayStay=numberOfDaysStayTF.getText();
        String totalAmount=totalAmountTF.getText();
        String roomNo=roomNumberTF.getText();
        String roomType=roomTypeTF.getText();
        String bed=bedTF.getText();
        String pricePerDay=pricePerDayForRoomTF.getText();
        String checkInDate=checkInDateTF.getText();
       
        if("".equals(roomNo)){
            CustomerCheckOutController.DisplayCustomerErrorCheckOut();
        }else{
            
        
        
        CustomerCheckOutController.UpdateCustomerCheckOut(numberOfDayStay, totalAmount, checkOut, id);
        
        CustomerCheckOutController.UpdateRoomTableStatus(roomNo);
                                                        
        CustomerCheckOutController.bill(id, name, mobileNumber, email,checkOut, numberOfDayStay, totalAmount, roomNo, roomType, bed,pricePerDay,checkInDate);
        
        CustomerCheckOutController.BillShowMessage(id);
        
        setVisible(false);
        new CustomerCheckOut().setVisible(true);
        }
    }//GEN-LAST:event_printBillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCheckOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTF;
    private javax.swing.JTextField bedTF;
    private javax.swing.JTextField checkInDateTF;
    private javax.swing.JTextField checkOutDateTF;
    private javax.swing.JTextField customerIdNumberTF;
    private javax.swing.JTextField customerMobileNumberTF;
    private javax.swing.JTextField customerNameTF;
    private javax.swing.JTextField customerNationalityIdNumberTF;
    private javax.swing.JTextField customerNationalityTF;
    private javax.swing.JTextField emailTF;
    private javax.swing.JTextField genderTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField numberOfDaysStayTF;
    private javax.swing.JTextField pricePerDayForRoomTF;
    private javax.swing.JButton printBill;
    private javax.swing.JButton resetBtn;
    private javax.swing.JTextField roomNumberTF;
    private javax.swing.JTextField roomTypeTF;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField totalAmountTF;
    // End of variables declaration//GEN-END:variables
}
